name: Pipeline for BlaBlaMower

on:
  push:
    tags:
      - v*.*.*

jobs:
  build_publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install poetry --user
        poetry install
    - name: Build Pyhton module
      run: poetry build
    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: "${{ secrets.PYPI_TOKEN }}"
    - name: Create GitHub release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          README.md
          CHANGELOG.md
          dist/*
