name: Pipeline for BlaBlaMower

on:
  push:
    branches:    
      - master
    tags:
      - v*.*.*


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install poetry --user
        poetry install
    - name: Build Pyhton module
      run: poetry build -f wheel
    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_TOKEN }}